[build]
builder = "NIXPACKS"
buildCommand = "yarn"

[deploy]
startCommand = "yarn medusa start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 