[build]
builder = "NIXPACKS"
buildCommand = "yarn"

[deploy]
startCommand = "cp .env.railway .env && yarn medusa start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[envs]
NODE_ENV = "production" 