[build]
builder = "NIXPACKS"
buildCommand = "yarn"

[deploy]
startCommand = "yarn medusa start"
healthcheckCommand = "yarn health"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[envs.production]
PORT = "9000"
NODE_ENV = "production"
MEDUSA_FF_WORKFLOWS = "false"
NODE_OPTIONS = "--dns-result-order=ipv4first" 